# Generated by Django 5.0.7 on 2024-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectImage', models.ImageField(upload_to='project_images/')),
                ('projectName', models.CharField(max_length=200)),
                ('projectTechnology', models.CharField(max_length=20)),
                ('projectDescription', models.TextField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['projectName'],
            },
        ),
    ]
