# Generated by Django 5.2 on 2025-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='projectTechnology',
            field=models.CharField(max_length=200),
        ),
    ]
