# Generated by Django 5.1.1 on 2024-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('title', models.CharField(max_length=200)),
                ('highlights', models.TextField(max_length=1000)),
                ('contributions', models.TextField(max_length=1000)),
            ],
        ),
    ]
