# Generated by Django 5.1.1 on 2024-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='contributions',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='highlights',
            field=models.TextField(max_length=10000),
        ),
    ]
